services:
  db:
    image: postgres:15
    container_name: butbalanced_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: jdp96n
      POSTGRES_DB: butbalanced
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.unit
    container_name: butbalanced_web
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: jdp96n
      DB_NAME: butbalanced
      POSTGRES_DB: bb
    volumes:
      - ./web:/var/www/html
      - ./unit-config.json:/docker-entrypoint.d/config.json:ro
    restart: unless-stopped

volumes:
  pg_data:
