services:
  db:
    image: postgres:15
    container_name: butbalanced_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: jdp96n
      POSTGRES_DB: butbalanced
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: ./web
    container_name: butbalanced_web
    ports:
      - "80:80"
      - "9003:9003"  # порт для Xdebug
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: jdp96n
      DB_NAME: butbalanced
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_MODE: "debug"

    volumes:
      - ./web:/var/www/html   # синхронизация файлов
      - ./web/xdebug_logs:/tmp  # логи Xdebug (опционально)
    restart: unless-stopped

volumes:
  pg_data:
