[PHP]
; Основные настройки
date.timezone = Asia/Novosibirsk
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300
memory_limit = 512M

; Настройки OPcache (для продакшена)
[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1

; Настройки Xdebug (для разработки)
[xdebug]
;zend_extension = xdebug.so
;xdebug.mode = debug
;xdebug.client_host = host.docker.internal  # для Mac/Windows
;# xdebug.client_host = 172.17.0.1          # для Linux
;xdebug.client_port = 9003
;xdebug.start_with_request = yes
;xdebug.log = /tmp/xdebug.log
;xdebug.idekey = PHPSTORM
;xdebug.discover_client_host = true

; Для Linux замени host.docker.internal на 172.17.0.1 или IP хоста
